# Generated by Django 4.1.7 on 2023-04-12 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="amount",
            new_name="sender_amount",
        ),
        migrations.RemoveField(
            model_name="moneyrequest",
            name="amount",
        ),
        migrations.AddField(
            model_name="moneyrequest",
            name="receiver_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moneyrequest",
            name="sender_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="receiver_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
            preserve_default=False,
        ),
    ]
