# Generated by Django 4.1.7 on 2023-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_rename_amount_transaction_sender_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneyrequest",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
